### PR TITLE
Provided detail on card indexes

### PR DESCRIPTION
**Pull request by csecht**
On line 217 I added a couple sentences explaining how cards are numbered.  At least that's how it works on my system. I thought it worth mentioning because it took me a while to figure out why there was a card0 on one host but not the other.

### CODE REVIEW

**Comment by Ricks-Lab** [comment]
From my experience, I don't think that card 0 is always the one with the monitor attached.  You can actually plug the monitor into any card, and the system doesn't alter the card numbering.  I have made a few errors by assuming something about card numbering...

**Comment by csecht** [comment]
Hmmm. On my host with a Pentium G5600 (Intel HD Graphics) and two RX570s, when I boot with the monitor connected to the motherboard DVI-D, the two AMD cards come up as card1 and card2, but when I boot with the monitor connected to the top RX570 DVI-D port, the cards come up as card0 and card1. (It seems that with Ubuntu a second graphics PCIe card is never recognized for video output). On my old host without onboard graphics, the monitor is connected to the top RX460 card, and that lists card0 and card1.

**Comment by Ricks-Lab** [comment]
I have just confirmed that my system with 3 RX Vega64's enabled on a x399 MB, the card with a monitor plugged into it is identified as Card 2 by amdgpu-utils and device 0 by BOINC.  On my systems, BOINC numbering is opposite of what the driver uses.  Perhaps this behavior is platform dependent.  Since we can not make such a precise statement as in your pull request, I suggest we close without merging it.  Let me know of any concerns.

**Comment by csecht** [comment]
Yes, I agree, close and don’t merge.

**Comment by Ricks-Lab** [comment]
Agreed to be less specific about card numbering as it appears to be inconsistent across various platforms.

**Pull request closed without merging**
