### PR TITLE
Deleting monitor-scrshot file for update

### PR DESCRIPTION
**Pull request by csecht**
Delete old amdgpu-monitor-scrshot.png and replace with new amdgpu-monitor-scrshot.png
amdgpu-monitor-scrshot
.png

### CODE REVIEW

**Comment by Ricks-Lab** [comment]
Can you try just copying the new image over the new one in your repository and then commit and push the change?  I think that should work.

**Comment by csecht** [comment]
I finally figure out how to work within my repository (duh), but not how to push.  So I uploaded the new image and made a pull request.  Will that work?

**Comment by Ricks-Lab** [comment]
Let’s give it a try. I don’t have experience making pull requests to a repository I don’t own.  If you clone my repository and create a local branch, can you push that branch?

**Comment by csecht** [comment]
Give me some time to learn local command-line git and how to sync my GitHub repository and branches. Working on it….

**Comment by csecht** [comment]
From my forked repository on GitHub, updated my old master using a pull request and merge from your master. That worked (on the second try).  I then replaced the amdgpu-monitor_scrshot.png file in Docs with a new one from my host. I don’t see an option to push that single file chance, but I can do a pull request for my master into yours. The problem (?) is that on 2 March I fumbled several other attempts at this and have several commits from that date which need to be ignored.  There doesn’t seem to be any good way for me to remove those bogus commits, so I don’t know what to do next.

**Pull request closed without merging**
