### PR TITLE
Create setup.py

### PR DESCRIPTION
**Pull request by smoe**
Heya,
Thank you for your work. I am currently preparing a Debian package for your utilities- you don't mind to see this uploaded to the distribution? The current plan of mine is to have two packagse for it - one for the module "GPUmodule" and the other for the utilities themselves. The running package name is "ricks-amdgpu-utils", which I hope to be just fine with you.
Cheers,
Steffen

### CODE REVIEW

**Comment by Ricks-Lab** [comment]
Hi Steffen,

I am fine with the plan! This is my first project that has had a significant number of users, so I hope it is robust enough for the potential of a wider distribution.  Since I have never had a project as a Debian package, I am not familiar with anything I would have to do in terms of updates.  Will it automatically use the latest official release?  Or is there a manual process?

I am planning to release v2.5.2 this weekend, so I will make an official release after I finish final prep.

Regards,
Rick

**Comment by smoe** [comment]
Hi Rick,
This is nice to hear. Do you happen to be using Debian or Ubuntu yourself? We could arrange for you to become a Debian maintainer so you can upload to Debian unstable whenever you want. That auto-migrates to Debian testing within 5 days. The devel release of Ubuntu picks that up when they see fit - typically within two weeks. The challenge is to backport which typically needs to be done manually and there is little motivation on my side to provide them since I am running testing or unstable everywhere.
So, I suggest to upload 2.5.2 to Debian and then we shall see how much that is adopted on popcon.debian.org.
Best,
Steffen

**Comment by Ricks-Lab** [comment]
Hi Steffen,

I am using Ubuntu.  Let me know what I need to do and I will give it a try.

Regards,
Rick

**Comment by smoe** [comment]
The first upload is on me - no need for you to do anything. I'll add everything to https://salsa.debian.org/science-team, I think (alternative would by the python-team), so you can patch bits and pieces without being bothered with the nitty gritty at day one. What you could help me with is an account of yours with salsa.debian.org and then a request to join the science-team - just mention that <moeller> is mentoring you for maintaining amdgpu-utils. I would also need an email address of yours for which you have (or plan to have) a GPG key with which you eventually sign uploads to the distribution. That email address is likely to receive its share of SPAM, so it should be an account that can handle it.
For smooth an consistent uploads to both Ubuntu and Debian, it may be easiest to become a Debian Maintainer (https://wiki.debian.org/DebianMaintainer).
Backports for Ubuntu I suggest to have as a PPA at first. I learned in the meantime that you are also into BOINC, so my first contact would be with https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/boinc about it. 
We still need to figure out how to contribute backports to Ubuntu when this is not a PPA. I can do backports for Debian as a start.

**Comment by Ricks-Lab** [comment]
* I have completed release [v2.5.2](https://github.com/Ricks-Lab/amdgpu-utils/releases/tag/v2.5.2)
* I have created a new email to support the debian interaction and added it to the setup.py file. 
* For the account on salsa.debian.org, is a guest account appropriate?

Also, one concern is that the required driver package from AMD is only officially offered for specific releases, so I have only verified functionality on those releases of Ubuntu.  This package only works if that package from AMD is installed.

**Comment by smoe** [comment]
I did a first upload to the salsa.debian.org server. That is where most contributors allow for some joint improvements of the packaging. At your leisure, please edit https://salsa.debian.org/science-team/ricks-amdgpu-utils/blob/master/debian/control with some better description than what I have yet come up with.

**Comment by Ricks-Lab** [comment]
I have created an account on salsa.debian.org, ricks-lab-guest, and have requested access to the science team.  My email for use with this project is rueikes.homelab@gmail.com

**Comment by Ricks-Lab** [comment]
@smoe 
I am not that familiar with the use of this file, and have a few questions:
* Is an entry required in order to access the icon files?
* Are there issues in how relative filenames are used in the project, especially for files like icons and the pciid files?

**Comment by smoe** [comment]
@Ricks-Lab 
I admit that the setup.py I created for amdgpu-utils was the first ever I have done. To answer your questions is hence a bit above me. I can only report that the data file that I added to have a functional amdgpu-ls just works with no further changes to your source tree.

Sidenote: The Debian package currently sits in the Debian "[nhttps://ftp-master.debian.org/new.htmlew queue]()", waiting for a manual review by the FTPmasters.

**Comment by Ricks-Lab** [comment]
@smoe 
So much to learn!  Seems like every day I am figuring out something new.  I think I need to dig into setup and requirements files a bit more.  amdgpu-ls doesn't have an icon, so it probably won't cause a problem, but plot, monitor, and pac do.  So I suspect they may not be found.  But not sure, since I don't understand how the distribution works.

**Comment by smoe** [comment]
I have only used the command line interface - was not aware of an icon :) For having your tools shown up in various desktops, I suggest to edit debian/menu (not existing) according to this "menu.ex" template by the dh-make package:
```
?package(#PACKAGE#):needs="X11|text|vc|wm" section="Applications/see-menu-manual"\
  title="#PACKAGE#" command="/usr/bin/#PACKAGE#"
```
The Debian policy has a section here https://www.debian.org/doc/debian-policy/ch-opersys.html#menus which I do not find too easy to follow. 
For icons to appear within the application I would just go and ignore anything Debian/Ubuntu-typical. Stackoverflow and friends I expect to have answers.

**Comment by smoe** [comment]
The package [ricks-amdgpu-utils](https://tracker.debian.org/pkg/ricks-amdgpu-utils) has just arrived in Debian untable. Its migration to the devel version of Ubuntu should happen within the next few days.

**Comment by Ricks-Lab** [comment]
I started using an IDE which made some code improvement opportunities more evident.  I also found/fixed one bug in the monitor utility.   It is version v2.6.0, but currently under testing.  When released, I may need help in updating the package on Debian.

**Pull request merged**
